In [2]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [13]:
import numpy as np
ar= np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand(1)

array([0.8510239])

In [16]:
np.random.rand(25)

array([0.16059908, 0.50631686, 0.17624628, 0.82089015, 0.52962764,
       0.13912909, 0.04169302, 0.22183421, 0.38883583, 0.43258176,
       0.1809073 , 0.05701935, 0.02938351, 0.5479998 , 0.34559388,
       0.97047782, 0.35018611, 0.04233827, 0.30748425, 0.08364052,
       0.83869022, 0.99098985, 0.6179061 , 0.04269385, 0.30690777])

In [24]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [37]:
ar=np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
ar[2,2]

13

In [39]:
ar[2,1]

12

In [42]:
ar[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [47]:
ar[0:3,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [49]:
ar[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [2]:
import numpy as np

In [5]:
mat=np.arange(1,26).reshape(5,5)

In [6]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [9]:
mat[-1]

array([21, 22, 23, 24, 25])

In [10]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
np.sum(mat)

325

In [13]:
np.std(mat)

7.211102550927978

In [16]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [17]:
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.arange(0,12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
mat.dtype

dtype('int32')

In [25]:
mat.shape

(5, 5)

In [28]:
np.ones(8).reshape(2,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.random.randint(1,100)

34

In [31]:
np.random.randint(0,100,20)

array([91, 28, 17, 18, 67, 69,  8, 36, 18,  6, 49, 51,  2, 21, 49,  9, 82,
        9, 60,  3])

In [32]:
result=np.random.randint(0,100,20)
result

array([ 1, 49, 21, 22, 14,  5, 11, 97, 43, 88,  6, 43, 92,  6, 50, 38, 65,
       88,  7, 92])

In [33]:
np.sort(result)

array([ 1,  5,  6,  6,  7, 11, 14, 21, 22, 38, 43, 43, 49, 50, 65, 88, 88,
       92, 92, 97])

In [2]:
import numpy as np
rarr=np.random.uniform(0,15,10)

In [3]:
rarr

array([10.11268623, 14.47391363,  8.14273058, 13.03707591, 10.80606171,
        2.95763051, 13.85296945,  0.75422033,  4.43009311, 10.95151092])

In [4]:
np.ceil(rarr)

array([11., 15.,  9., 14., 11.,  3., 14.,  1.,  5., 11.])

In [5]:
np.floor(rarr)

array([10., 14.,  8., 13., 10.,  2., 13.,  0.,  4., 10.])

In [6]:
np.round(rarr)

array([10., 14.,  8., 13., 11.,  3., 14.,  1.,  4., 11.])

In [8]:
mat=np.arange(0,25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
np.sum(mat,axis=0)

array([50, 55, 60, 65, 70])

In [12]:
np.min(mat,axis=0)

array([0, 1, 2, 3, 4])

In [11]:
np.max(mat,axis=0)

array([20, 21, 22, 23, 24])

In [13]:
np.var(mat,axis=0)

array([50., 50., 50., 50., 50.])

In [15]:
np.std(mat,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [18]:
nv=np.full(10,'NaN')

In [19]:
nv[5]=200

In [20]:
nv

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', '200', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [21]:
np.arange(100,150)#16

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [24]:
code=np.nonzero([1,0,2,5,8,0,0,9,0])#19
code

(array([0, 2, 3, 4, 7], dtype=int64),)

In [25]:
np.flip(code)#17

array([[7, 4, 3, 2, 0]], dtype=int64)

In [26]:
np.arange(0,25).reshape(5,5)#18

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
m=np.ones((10,10))#20
m


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
m[1:9,1:9]=0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
h=np.ones((8,8))
h

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
h[::2,::2]=0
h[1::2,1::2]=0
h

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])