# SK-Learn


In [12]:
import numpy as np

In [13]:
x=np.arange(10).reshape(5,2)
y=range(5)

In [14]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
list(y)

[0, 1, 2, 3, 4]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [18]:
x_train

array([[4, 5],
       [0, 1],
       [8, 9]])

In [19]:
x_test

array([[2, 3],
       [6, 7]])

In [20]:
y_train

[2, 0, 4]

In [21]:
y_test

[1, 3]

In [22]:
train_test_split(x,y)

[array([[0, 1],
        [2, 3],
        [6, 7]]),
 array([[8, 9],
        [4, 5]]),
 [0, 1, 3],
 [4, 2]]

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model=LinearRegression()

In [25]:

model.fit(x_train,y_train)

LinearRegression()

In [26]:
prediction=model.predict(x_test)
prediction

array([1., 3.])

In [27]:
#it is used to create continous results 
import pandas as pd

In [28]:
data1=pd.read_csv("/Users/macbppk/Desktop/advertising.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/Users/macbppk/Desktop/advertising.csv'

In [ ]:
data2=pd.read_csv("")

In [ ]:
data3=pd.read_csv("")

In [ ]:
data1

In [ ]:
data1.info()

In [ ]:
housing=pd.read_csv("/Users/macbppk/Desktop/USA_Housing.csv")

In [29]:
X = data1[['Age','Area Income','Daily Internet Usage','Male']]
Y = data1['Clicked on Ad']

NameError: name 'data1' is not defined

In [30]:
X

NameError: name 'X' is not defined

In [31]:
Y

NameError: name 'Y' is not defined

In [32]:
from sklearn.model_selection import train_test_split

In [33]:

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=101)


NameError: name 'X' is not defined

In [34]:
train_test_split(X,Y,test_size=0.4,random_state=101)

NameError: name 'X' is not defined

In [35]:
from sklearn.linear_model import LinearRegression
model1=LinearRegression()

In [36]:
model1.fit(X_train,Y_train)

NameError: name 'X_train' is not defined

In [37]:
model1.fit(X_train,Y_train)
prediction1=model1.predict(X_test)
prediction1

NameError: name 'X_train' is not defined

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
import seaborn as sns

In [50]:
t=sns.load_dataset('iris')
t.head()

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [ ]:
t.info()

In [ ]:
X= t[['sepal_length','sepal_width','petal_length','petal_width']]
Y= t['species']

In [ ]:
X

In [ ]:
Y

In [ ]:
from sklearn.linear_model import LinearRegression


In [ ]:
p=LinearRegression()

In [ ]:
p

In [ ]:
p.fit(X_train,Y_train)
prediction1=p.predict(X_test)
prediction1

In [ ]:
#3 mark question
import numpy as np
X=np.arange(10).reshape(5,2)
y=range(5)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x,y)
model=LinearRegression()
model.fit(x_train,y_train)

In [ ]:
import pickle   #save py object in file

In [42]:
with open('LRmodel','wb')as f:  #b =binary form
    pickle.dump(model,f)

In [43]:
with open('LRmodel','rb')as f:
    saved_model=pickle.load(f)

In [44]:
saved_model.predict(x_test)

array([1., 3.])

In [45]:
saved_model.predict([[10,11]])

array([5.])

In [46]:

saved_model.predict([[14,15]])

array([7.])

In [47]:
import joblib

In [48]:
f1='LR_model.sav'
joblib.dump(model,f1)

#load model
joblib_model=joblib.load(f1)

#predict values
joblib_model.predict([[10,11]])


array([5.])

In [ ]:
from flask import Flask,jsonify,request
import pickle

app= Flask(__name__)

@app.route('/')
def hello():
    return"Hello World"

@app.route('/<string:name>/')
def helloname(name):
    return "hello" + name

@app.route('/<int:x1>/<int:x2>/')
def test(x1,x2):
    f=open('LRmodel','rb')#open file in read mode
    saved_model=pickle.load(f)#Load saved model using pickle
    prediction = saved_model.predict([[x1,x2]])
    print(prediction)
    return 'output :'+str(prediction[0])
    
    
app.run(host='0.0.0.0', port=106)
    

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:106
 * Running on http://127.0.0.1:106
Press CTRL+C to quit
127.0.0.1 - - [02/May/2024 12:57:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 12:57:07] "GET /favicon.ico HTTP/1.1" 308 -
127.0.0.1 - - [02/May/2024 12:57:07] "GET /favicon.ico/ HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 12:59:26] "GET /vrund/ HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 12:59:26] "GET /favicon.ico/ HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 12:59:44] "GET /8/9/ HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 12:59:44] "GET /favicon.ico/ HTTP/1.1" 200 -


[4.]
